Metrics/LineLength:
  Max: 125
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoreCopDirectives: false
  IgnoredPatterns: []

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
